baseurl = "/"
# language specifications
languageCode = "en-US"
hasCJKLanguage = true
# content related
title = "Liang's tracks"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
# other configurations
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "My simple everyday blog site."
    footer = "&copy; Liang Zhang 2017-2018 | [Github](https://github.com/psychelzh)"
