---
title: 工作总结、反思和计划
author: 张亮
date: '2018-02-27'
slug: work-plan
categories:
  - Work
tags:
  - 总结
---

# 工作总结

## 概述

从毕业入职后开始，心中一直有一个目标，就是全面修正和优化现有所有的测评题目，保证题目交互流畅、配置正确和测评结果的科学性。

* **保证题目的交互流畅方面。**在网页端和APP端多做测试，找出题目交互过程中的漏洞和需要优化的流程。所有的调整都已整理进文档中。
* **保证题目的配置正确方面。**搜集和整体使用单个题目对应范式的期刊论文，总结论文中这些范式的常用配置和注意事项，然后对比已有题目的配置，并做出响应的调整。所有的调整都已整理进文档中。
* **保证题目测评结果的科学性方面。**目前这部分工作主要计划采用测评的信度和效度指标、测评结果表现出的年龄发展情况和测评指标分布形状综合来判断。但是出于数据缺失严重等原因，这些工作在目前处于半搁置状态。

除去测评题目相关工作外，剩下的主要工作就是脑计划的数据分析、整理和报告的生成。

## 具体完成内容

* 全面更新了所有测评题目的开发情况（交互过程需要优化的提交BUG描述）
* 更新了以下任务的设计文档
    + 方向达人（根据NIH的设计思路，修正为两个版本，高龄版和低龄版）
    + 捉虫
    + 思维转换和反应转换
    + 吹气球
    + 记忆尾巴
* 整理脑计划数据和生成报告

# 工作计划

## 概述

新年工作任务更多更杂，但是整体上来看主要包括两部分任务：

1. 进一步完善认知测评类题目的设计；
1. 小学语文训练项目的开发与发展。

## 详细规划

### 测评题目设计

* 继续更新测评题目的设计文档，保证题目的**交互流程说明**清晰明了、**配置**文档说明完整等。
* 根据已有的测评数据，进一步进行测评题目各项技术指标的确定：**能力表现指标**、**信度和效度**、**常模**等。
* 开始感知觉能力测评题目的设计。

### 小学语文训练

此项目目前刚刚起步，由于自己在教育方面经验欠缺，所以前期需要较多时间了解小学语文教育的特点和具体要求。具体说来：

* 明确语文训练的定位：训练语文相关的能力、教授课本知识等。
* 寻找语文训练的合适游戏。
* 制定语文训练的课程规划。

# 工作反思

自毕业以来，常常感到很强的无力感和迷茫。仔细想来，有这样一些个人因素导致这些问题：

1. 对工作需要达到的目标常常理解不到位，同时对反馈不足够重视。这样导致自己工作时很多内容不符合要求，而且耗去较多时间去做不必要做的事情。
1. 对工作中遇到的困难没有足够动力去克服，容易遇到困难就搁置工作。这一点是后面需要主要锻炼的。
1. 思考太多，行为犹豫不决。

鉴于这些，在以后的工作中，需要注意到：

1. 工作时注意沟通，多思考目标是否明确，实时寻找反馈和解决困难的方法。
1. 做事情更加果断一些。
